export const CHECKOUT = "CHECKOUT";
export const CHECKOUT_SUCCESS = "CHECKOUT_SUCCESS";
export const CHECKOUT_FAIL = "CHECKOUT_FAIL";
export const RESET_CHECKOUT_STATUS = "RESET_CHECKOUT_STATUS";

export const FETCH_MY_ORDERS = "FETCH_MY_ORDERS";
export const FETCH_MY_ORDERS_SUCCESS = "FETCH_MY_ORDERS_SUCCESS";
export const FETCH_MY_ORDERS_FAIL = "FETCH_MY_ORDERS_FAIL";
export const RESET_FETCH_MY_ORDERS_STATUS = "RESET_FETCH_MY_ORDERS_STATUS";

export const PATCH_ORDER = "PATCH_ORDER";
export const PATCH_ORDER_SUCCCESS = "PATCH_ORDER_SUCCCESS";
export const PATCH_ORDER_FAIL = "PATCH_ORDER_FAIL";

export const FETCH_ALL_ORDERS = "FETCH_ALL_ORDERS";
export const FETCH_ALL_ORDERS_SUCCESS = "FETCH_ALL_ORDERS_SUCCESS";
export const FETCH_ALL_ORDERS_FAIL = "FETCH_ALL_ORDERS_FAIL";
export const RESET_FETCH_ALL_ORDERS_STATUS = "RESET_FETCH_ALL_ORDERS_STATUS";
