export const GET_CART = "GET_CART";
export const GET_CART_SUCCESS = "GET_CART_SUCCESS";
export const GET_CART_FAIL = "GET_CART_FAIL";
export const RESET_GET_CART_STATUS = "RESET_GET_CART_STATUS";

export const ADD_TO_CART = "ADD_TO_CART";
export const ADD_TO_CART_SUCCESS = "ADD_TO_CART_SUCCESS";
export const ADD_TO_CART_FAIL = "ADD_TO_CART_FAIL";
export const RESET_ADD_TO_CART_STATUS = "RESET_ADD_TO_CART_STATUS";

export const UPDATE_CART = "UPDATE_CART";

export const DELETE_ITEM_FROM_CART = "DELETE_ITEM_FROM_CART";
export const DELETE_ITEM_FROM_CART_SUCCESS = "DELETE_ITEM_FROM_CART_SUCCESS";
export const DELETE_ITEM_FROM_CART_FAIL = "DELETE_ITEM_FROM_CART_FAIL";
